import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './format';

interface CustomerStatementParams {
  customer: any;
  entries: any[];
  periodLabel: string;
  storeName?: string;
  summary: {
    totalPurchase: number;
    totalPaid: number;
    outstanding: number;
  };
}

export function generateCustomerStatementPdf({
  customer, entries, periodLabel, storeName = 'All Stores', summary
}: CustomerStatementParams) {
  const doc = new jsPDF() as any;

  // Add theme header
  doc.setFillColor(79, 70, 229); // Indigo
  doc.rect(0, 0, 210, 30, 'F');

  // Business Name
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('BUILD ERP', 15, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Customer Account Statement', 15, 24);

  // Statement Label
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('STATEMENT OF ACCOUNT', 130, 20);

  // Business / Store Info
  doc.setTextColor(80, 80, 80);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Store:            ${storeName}`, 15, 45);
  doc.text(`Period:           ${periodLabel}`, 15, 51);
  doc.text(`Generated:    ${new Date().toLocaleString('en-IN')}`, 15, 57);

  // Customer Details
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 120, 45);
  doc.setFont('helvetica', 'normal');
  doc.text(`Customer Name:  ${customer.name}`, 120, 51);
  doc.text(`Mobile Number:  ${customer.mobile || '-'}`, 120, 57);
  doc.text(`GSTIN/GST:      ${customer.gst_number || 'N/A'}`, 120, 63);

  // Separator line
  doc.setDrawColor(220, 220, 220);
  doc.line(15, 70, 195, 70);

  // Table Headers
  const headers = [['Date', 'Type', 'Reference', 'Description', 'Debit (Dr)', 'Credit (Cr)', 'Running Bal']];
  
  // Table Rows
  const rows = entries.map((entry: any) => {
    const dateStr = formatDate(entry.date || entry.created_at);
    const typeStr = String(entry.entry_type || entry.type || '-').toUpperCase();
    const refStr = entry.reference_no || entry.invoice_no || '-';
    const descStr = entry.description || entry.narration || '-';
    const debit = entry.debit_amount ? formatCurrency(entry.debit_amount) : '-';
    const credit = entry.credit_amount ? formatCurrency(entry.credit_amount) : '-';
    const runningBal = formatCurrency(entry.balance || entry.running_balance || 0);

    return [dateStr, typeStr, refStr, descStr, debit, credit, runningBal];
  });

  autoTable(doc, {
    head: headers,
    body: rows,
    startY: 75,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] }, // Royal Blue
    styles: { fontSize: 8.5, cellPadding: 3, font: 'helvetica' },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 22 },
      2: { cellWidth: 22 },
      3: { cellWidth: 'auto' },
      4: { halign: 'right', cellWidth: 24 },
      5: { halign: 'right', cellWidth: 24 },
      6: { halign: 'right', cellWidth: 26 },
    },
  });

  const finalY = doc.lastAutoTable.finalY + 12;

  // Account Summary Card
  doc.setFillColor(248, 250, 252); // bg-slate-50
  doc.rect(15, finalY, 180, 28, 'F');
  doc.setDrawColor(226, 232, 240); // border-slate-200
  doc.rect(15, finalY, 180, 28, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('TOTAL PURCHASES', 25, finalY + 10);
  doc.text('TOTAL PAID', 85, finalY + 10);
  doc.text('OUTSTANDING BAL', 145, finalY + 10);

  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(formatCurrency(summary.totalPurchase), 25, finalY + 20);
  doc.text(formatCurrency(summary.totalPaid), 85, finalY + 20);

  // Outstanding in red if positive
  if (summary.outstanding > 0) {
    doc.setTextColor(220, 38, 38); // text-red-600
  } else {
    doc.setTextColor(22, 163, 74); // text-green-600
  }
  doc.text(formatCurrency(summary.outstanding), 145, finalY + 20);

  // Footer notes
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This is a computer generated account statement. Generated by BUILD ERP PWA.', 15, 285);

  return doc;
}
